version: 2
updates:
  - package-ecosystem: npm
    directory: /
    labels:
      - dependencies
    schedule:
      interval: monthly
    groups:
      development-dependencies:
        dependency-type: development
    open-pull-requests-limit: 2
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - skip-changelog
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]
    open-pull-requests-limit: 2
