export const INSTRUCTION_START_MARKER = '<!-- commitprompt:start -->'
export const INSTRUCTION_END_MARKER = '<!-- commitprompt:end -->'

export const PROJECT_INSTRUCTION_BODY = `## Commit generation

- Inspect the repository instructions, status, staged diff, and unstaged diff
  before proposing a commit message.
- Do not stage files unless the user explicitly asks you to.
- Run \`commitprompt types --json\`, \`commitprompt scopes --json\`, and
  \`commitprompt instructions --json\` to load the repository rules.
- Pass all six structured fields to \`commitprompt format --json\`, then validate
  the exact message with \`commitprompt validate --json\`.
- Only run \`commitprompt commit --yes --json\` when the user explicitly
  authorizes a commit. Never stage unrelated files or bypass Git hooks.
- Review messages generated by Zed or VS Code. The \`commit-msg\` hook is the
  final authority and rejected messages must be corrected, not forced through.`

export const PROJECT_INSTRUCTION_SECTION =
  `${INSTRUCTION_START_MARKER}\n${PROJECT_INSTRUCTION_BODY}\n${INSTRUCTION_END_MARKER}`

export const AGENT_SKILL_TEMPLATE = `---
name: commitprompt
description: >-
  Generate, format, validate, and explicitly authorize Conventional Commits
  with the repository's installed Commitprompt CLI.
---

# Commitprompt commit workflow

${PROJECT_INSTRUCTION_BODY}

Use empty strings for omitted optional fields when calling \`format\` or
\`commit\`. Never drive the interactive questionnaire from an AI agent.
`
